const cancelList = [
  'ser gado demais',
  'ser atraente demais',
  'procrastinar demais',
  'ser uma delícia',
  'ser poser',
  'ser insuportável',
  'ser atraente demais',
  'ser inadimplente no Serasa',
  'ser trouxa',
  'ser corno',
  'se considerar incancelável',
  'ser insensível',
  'não fazer nada',
  'ser BV',
  'ser inteligente demais',
  'ser comunista',
  'ter virado o Coronga',
  'ter muita preguiça',
  'ser corno',
  'debochar demais',
  'pedir muito biscoito',
  'ter charme demais',
  'ser uma grande gostosa',
  'se atrasar sempre',
  'ser boy lixo',
  'contar muita piada ruim',
  'ser impaciente demais',
  'ser ancap',
  'ser gay',
  'ser hétero',
  'ser prata',
  'ser monochampion',
  'ser tóxico',
  'ser irritante',
  'mamar demais',
  'banir Ezreal',
  'jogar ARAM',
  'jogar URF',
  'ser da PanelaCraft',
  'ser mono Yuumi',
];

module.exports = cancelList;
