const quotes = [
  `#1: "Tá de castigo, vai ficar com o VIP" - Ezreal Blindado`,
  `#2: "Ela vai vir por cima e eu vou fugir por baixo." - Blindado, Ezreal`,
  `#3: "Se falam de vc pelas costas, é sinal que você tá na frente." - CARRARA, Agostinho.`,
  `#4: manda foto do pézinho - Arb`,
  `#5: "eu de pau" - bot`,
  `#6: ''cócócócócó'' -loro`,
  `#7: "a menina era o correio" blindado, ez 2019`,
  `#8: ''achei que isso eram bolas de um bovino'' -ez`,
  `#9: "É goteira pra pingar tanto?" - Alexia FreeFire`,
  `#10: "Seu exploradorzinho!" - MyNick`,
  `#11: "ai eu achei que o lobo era do mal" - ez`,
  `#12: "esse eu só nao morri pq eu sobrevivi" ez`,
  `#13: "sorte que quem bate esquece" -ez`,
  `#14: "eu não tenho flash,mas não sou eu que preciso" -blindado,ezreal`,
  `#15: "tudo que eu falo agora é citaçãozinha" -blindado,ez`,
  `#16: "o lee sin tava muito saudável, sera que ele comeu a fruta?" - ez `,
  `#17: "motivacional do Gaara" by Ezrealblindado`,
  `#18: "alem de corno eh pequeno" - Blindado, Ezreal`,
  `#19: "eu sou corno e queria pegar akele anjo"`,
  `#20: "O fogo queima" By EzBlindado`,
  `#21: "amigo se viu minha chave?"`,
  `#22: "senta assim quem se garante" - ez blindado`,
  `#23: "GABRUEK VV EH A PESSOA MAIS OACIENFISSOAA" - freefire louca de alcool`,
  `#24: "surfa aqui no meu colo" - ez blindadoo`,
  `#25: ''ah, n eh alexio né, eh alex'' - ezreal blindado`,
  `#26: "esse cara de red blue ta com asas né mano" - ezreal blindado`,
  `#27: "eu fiz isso aqui pra stackar o contador de ult mais rapido, viu?" -Ezreal Blindado`,
  `#28: "w está para vv assim como corno está para como" -ezreal blindado`,
  `#29: "filosofia do pão e circo, aqui é o circo de soled e eu sou o pão, mano"- ezreal blindado`,
  `#30: "calado gabriel, tu farma que nem um animal" - alexia`,
  `#31: "eu achando q tav a farmando gota to farmando time out" -eodanieu`,
  `#32: "ezrealblindado timed out arbiht for 600 seconds."`,
  `#33: "hoje vou ensinar uma brincadeira com palitos de fosforos. Primeiro voce senta, depois voce mama" - ezreal blindado`,
  `#34: "comedor de esposas? eu to sendo a esposa né, cara ta me jantando aqui" -ezreal blindado`,
  `#35: "nunca mamei assim tão rápido mano" -ezreal blindado, contra um urgot`,
  `#36: "ufa, uma soraka jungle, agora to calmo" - ezreal blindado`,
  `#37: "aru?" "a vai toma no cu" -arbiht e aru`,
  `#38: "me lanso na brasa fdp" - blaze`,
  `#39: "se tivesse de dança taria vivo" "mas eu tava de dança." Ez bom e EZ ez`,
  `#40: "shhh estou meditando" - master yi`,
  `#41: "do que vcs tao falando eu fui lavar o pinto" -graves tiltado com pinto cheiroso`,
  `#42: "queimaram o fogo aqui mano?" -ezreal brisado`,
  `#43: "num certo dia, a @axeliaff foi comprar pão, pronto @axeliaff, empreguei você numa frase LUL" - JuliooZC`,
  `#44: "ser loro, ser um papagaio"`,
  `#45: "vc eh grande mas nao eh dois, eu sou pequeno mas nao sou metade" URAMESHI, yusuke`,
  `#46: "[...] eu dou a bunda" -arb`,
  `#48: "lol é lol" - ezreal blindado`,
  `#49: "fernvndx da camisa clothing" - ezreal blindado`,
  `#50: "pode me colocar fogo, naoa dianta colocar fogo no que já é quente" - ezreal blindado após levar um ignite`,
  `#51: "nao me come nao amigo, eu sei que eu sou gotoso, mas..." -ezreal blindado`,
  `#52: "vagabundo veio VAGABUNDEANDO" - ezreal blindado`,
  `#53: "pau da alexia até ficou mole, que judiação" -ezreal blindado`,
  `#54: "radpet? o que eh um radpet? radical petista?" -ezreal blindado`,
  `#55: "saude pau no cu" -@jakeakuma`,
  `#56: "ela comprou uma longa pra me ferrar, mas isso nao vai ficar assim. Vai ficar pior" -ez blindado contra uma riven 2/0 em 3 minutos`,
  `#57: "tentei fazer a boa, fiz a má" - ez blindado`,
  `#58: "sabe q q o peixe faz o dia todo? nada " - dania pão`,
  `#59: "imagina um pau high elo" -ezreal 'bebado' blindado`,
  `#60: "o que eu fiz com o lol? nunca mais eu encontro a cor. Só sei que vai ficar cinza agora né, desgraçado" - ez após ser amassado por um trynda`,
  `#61: "Diabo de capeta" by ez`,
  `#62: "mono ez n tem local de fala" -Degalles`,
  `#63: "A casa caiu pra toda a panela"- Ezreal Blindado`,
  `#64: "meu deus rafael" - ezreal blindado`,
  `#65: "to achando que eh bonito ser feio ne" - ezreal blindado após errar uma ult obvia`,
  `#66: "O Graves adora planta, principalmente o caule" — Blindado, Ezreal. 2020.`,
  `#67: "esse jogo ja foi pro rato" -BLINDADO, ez`,
  `#68: "não sou o crime" -ez`,
  `#69: "Não é isso daqui que vai me abalar... Tá abalou muito" — Blindado, Ezreal`,
  `#70: "já é, jacaré" -daniel de life is strange 2`,
  `#71: "ih alá, ultou achando que eu ja acertar, mas ela esqueceu que sou ruim" -ez após errar uma ult e a Lulu ultar o adc`,
  `#72: "eu gosto de beijar a rapazeada" -ezreal blindado`,
  `#73: "N ACESSO SITE VAGABUNDO" - Ez`,
  `#74: "que música eh essa velho? eh a música da vitória, acabei de me dar conta"- ez ao som dr Zé Vaqueiro- Se você se entregar`,
  `#75: "voces acham que é bonito brigar com pau???" -ezreal BULLY blindado`,
  `#76: "eu vou dar a flor pra ele dar o pau"- ezreal BULLY blindado`,
  `#77: " com amigas dessas não precisa nem de amigos" eliana_pequena`,
  `#78: escalar a montanha cresce o pé`,
  `#79: "sou de fronteira de sp com ms, posso comer como possível?" ezreal dando miss click na mensagem do candy`,
  `#80: "o trem eh foda" - tia boomer do master chef`,
  `#81: EH O BLINDAS`,
  `#82: “PULEI NO COLO DO PATATI” -EZREAL BLINDADO`,
  `#83: "add lindas zap" - ezreal blindado após ser crucificado pelo jungler`,
  `#84: "favor não fomentar a conversinha, grato" - ezreal blindado`,
  `#85: "os mlk tao parecendo criança" - ezreal blindado sobre master chef junior`,
  `#86: "sera que isso que to fazendo é ilegal? eu to passando só a cabeça"- ezreal blindado, sem contexto`,
  `#87: " faker ja ganhou algum cblol?" - @drezonho`,
  `#88: "master yi kids"- bz elindado`,
  `#89: "temos nanadores mas n temos mamadores" -`,
  `#90: "segundo freud estamos apenas mamando" @Beascoito`,
  `#91: "chupa minha teta" - ezreal blindado`,
  `#92: "o homem forte se defende sozinho,o homem mais forte defende os outros" - boi ben, RIP`,
  `#93: "o boi morreu e ele não fez nem um churrasco, NA fazendeiro" - ezreal blindado sobre a morte do boi ben`,
  `#94: "robô gigante obrigando inocente a empinar moto por 1000$" - Jayce Blindado`,
  `#95: "hehehe"- ovonivia`,
  `#96: "200 X 200, que grandao" - ezreal olhando para seu blindado`,
  `#97: "vove e te aviso" - Blindado, Ezreal`,
];

module.exports = quotes;
